development:
  adapter: postgresql
  database: karmaville_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: karmaville_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: karmaville
  host: localhost
  pool: 5
  timeout: 5000
