
development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: rails_client_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: rails_client_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: rails_client
  pool: 5
  timeout: 5000